### ISSUE TITLE
Suggestion for certificate handling

### ISSUE THREAD

**Issue by torevalley** [SignalK/signalk-server-node#907] opened 2019-12-05 06:25 UTC
Hi,
Right now the server pulls the certificate with specific file names from the .signalK directory.
I suggest adding support for letsencrypt certificates and certbot for management of the certificates.
If you use certbot you will have a valid and automatically updated certificate at "the end" of a symbolic link. If you can configure signalK to use a certificate made available via a symbolic link I think this will work and make life a lot easier in terms of certificate management.
When setup this way the check of access rights to the certificate can be skipped as well.

**Comment by tkurki** [comment] 2019-12-05 14:10
A good idea. 

What would the configuration look like? A checkbox _use Certbot_ and text field to specify the hostname?

I have my DNS in Route 53 and I believe I have someplace poc code for a server plugin full solution that would use Certbot with DNS Challenge to update the certificate, but just offloading certificate management totally to Certbot is a better strategy.

**Comment by torevalley** [comment] 2019-12-05 19:19
Agree I have my DNS at one.com and renew with a DNS challenge as well.
I'm not sure and do not remember if you can influence the symbolic link, mu guess is that you cannot.
So Yes I think a Certbot checkbox and a domain/hostname whatever the cert is issued to.
And some instructions like if you get a *.domain.se cert you need to specify the domain.se as 
you domain. but I guess that is all part of certbot.
Alternatively you just have a config where you enter the symbolic link to use for certificate
like /etc/letsencrypt/live/dronten.dahlarna.se and if configured and "target" exists use this as the certificate files there instead of the .*pem files in the .signalK directory.
This is copied from the readme file in the live symbolic link.

The certbot live directory will contain the following files:
This directory contains your keys and certificates.

`privkey.pem`  : the private key for your certificate.
`fullchain.pem`: the certificate file used in most server software.
`chain.pem`    : used for OCSP stapling in Nginx >=1.3.7.
`cert.pem`     : will break many server configurations, and should not be used
                 without reading further documentation (see link below).

We recommend not moving these files. For more information, see the Certbot
User Guide at https://certbot.eff.org/docs/using.html#where-are-my-certificates.

The correct files to use is the privkey and fullchain ( I guess this is already known :))

Of course you SignalK box would have to fulfill the requirements to run certbot in an automatic way :)

**Comment by torevalley** [comment] 2019-12-05 19:59
Thinking a few more minutes...

Why not just have two separate config items for the key and the cert.
If you use certbot you can enter the symbilic linke to the live files...
If you use something else as long as you can point out a valid cert and key file in your config, symbolic or not just use the files configured...

**Comment by tkurki** [comment] 2019-12-06 08:44
I think that just adding symlinks (or if that doesn't work hard links) to the cert files where the server expects the files to be under `.signalk` will allow you to use certbot managed keys already today. The strict access check may be a problem.

If we do something to improve certbot usage it should be as user friendly as possible. From a user's point of view the intent is to go tell the servert : _Use certbot managed certificate for hostname x.y.z_ and not care about details.

Supporting arbitrary key locations is another matter, but I don't think that is needed. At least I haven't heard anybody about it.

**Comment by torevalley** [comment] 2019-12-06 15:50
I hear you, but in that case I guess that certbot should be part of the distribution as well.
And I know off-topic here but still..
If I want to try pointing signalK towards a sym or hardlink now, where can I do that?
Is there a config somwhere?
Or maybe remove the cert and key file and replace the with sym links?

**Comment by tkurki** [comment] 2019-12-09 14:50
I would put this in a plugin if it were possible, but this is part of the server core. I think it is perfectly ok to add this and just point to their documentation for running it.

I think my certbot setups just copied the relevant files to where the server expects them to be. Please experiment & share your finding. The permission check is easy to find and just manually edit it away if that gives you trouble, then we can devise a plan for a longer term solution.

**Comment by torevalley** [comment] 2019-12-09 18:24
OK sounds like a plan, can you point me to the relevant parts of the code since I have never been in there :)

**Comment by tkurki** [comment] 2019-12-25 09:13
Duplicate of #340.

**Closed by tkurki** 2019-12-25 09:13 UTC
