### ISSUE TITLE
Warning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-server-node#163] opened 2017-03-10 20:30 UTC
I saw this while running a test instance in a VM:

```
GET /favicon.ico 304 13.811 ms - -
  signalk-server:interfaces:tcp Connected:1 ::ffff:192.168.122.1:44328 +47s
  signalk-server:interfaces:tcp Close:false 1 ::ffff:192.168.122.1:44328 +6s
  signalk-server:interfaces:tcp Connected:2 ::ffff:192.168.122.1:44330 +98ms
  signalk-server:interfaces:tcp Close:false 2 ::ffff:192.168.122.1:44330 +715ms
(node:1420) Warning: Possible EventEmitter memory leak detected. 11 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:1420) Warning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:1420) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:1420) Warning: Possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit
(node:1420) Warning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by tkurki** [comment] 2017-03-11 10:35
I have  had this happen 
- after my laptop has been sleeping 
- when trying to play back a short log file, causing the file to be repeatedly opened in quick succession

It is related to provider pipeline streams, but have not been able to pinpoint the exact mechanism and since there are no noticeable ill effects have concluded that fixing is not worth the potentially large effort.

Duplicate of #24.

**Closed by tkurki** 2017-03-11 10:35 UTC
